Vagrant.configure ("2") do |config|
    config.vm.define "soumansoS" do |server|
        server.vm.hostname = "soumansoS"
        server.vm.box = "bento/debian-12"
        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.provider "virtualbox" do |vm|
            vm.memory = 1024
            vm.cpus = 2
            vm.name = "soumansoS"
        end
    end

    config.vm.define "soumansoSW" do |worker|
        worker.vm.hostname = "soumansoSW"
        worker.vm.box = "bento/debian-12"
        worker.vm.network "private_network", ip: "192.168.56.111"

        worker.vm.provider "virtualbox" do |vm|
            vm.memory = 1024
            vm.cpus = 2
            vm.name = "soumansoSW"
        end
    end
end
